name: test_transaction
description: An app for storing transactions
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.1.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  flutter_bloc: 8.1.3
  cloud_firestore: 4.8.3
  random_string_generator: 2.0.0
  firebase_auth: 4.7.1
  firebase_core: 2.15.0
  flutter_secure_storage: 8.0.0
  meta: 1.9.1
  bloc: 8.1.2
  fl_chart: 0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2
  json_serializable: 6.7.1
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
